// Categories shown in the filter chip rail
export const CATEGORIES = [
  "Plumbing",
  "Electrical",
  "Home Cleaning",
  "Carpentry",
  "Painting",
  "Appliance Repair",
];

// Demo providers used to seed Firestore the first time the app runs,
// so the "at least 6 providers" requirement is met out of the box.
// Their doc ids are fixed (seed-1..seed-6) so seeding is idempotent —
// these are demo profiles only and cannot log in as themselves.
export const SEED_PROVIDERS = [
  {
    id: "seed-1",
    name: "Rafiq Ahmed",
    business: "Ahmed Plumbing Works",
    service: "Plumbing",
    location: "Gulshan-e-Iqbal, Karachi",
    experience: 9,
    price: 1500,
    priceUnit: "visit",
    bio: "Leak repairs, pipe fitting, and bathroom installs. Same-day visits across central Karachi.",
    rating: 4.7,
    reviewCount: 3,
    available: true,
  },
  {
    id: "seed-2",
    name: "Bilal Khan",
    business: "SparkFix Electricals",
    service: "Electrical",
    location: "DHA Phase 5, Karachi",
    experience: 6,
    price: 1800,
    priceUnit: "visit",
    bio: "Licensed electrician for wiring, fault-finding, and smart-home installs.",
    rating: 4.9,
    reviewCount: 2,
    available: true,
  },
  {
    id: "seed-3",
    name: "Sana Malik",
    business: "Sparkle Home Cleaning",
    service: "Home Cleaning",
    location: "Clifton, Karachi",
    experience: 4,
    price: 2500,
    priceUnit: "job",
    bio: "Deep-cleaning crew for apartments and offices. Bring our own supplies.",
    rating: 4.6,
    reviewCount: 5,
    available: true,
  },
  {
    id: "seed-4",
    name: "Imran Sheikh",
    business: "Sheikh Woodcraft",
    service: "Carpentry",
    location: "North Nazimabad, Karachi",
    experience: 12,
    price: 2000,
    priceUnit: "visit",
    bio: "Custom furniture, door and cabinet repair, on-site fitting.",
    rating: 4.8,
    reviewCount: 4,
    available: false,
  },
  {
    id: "seed-5",
    name: "Farhan Qureshi",
    business: "ColorCraft Painters",
    service: "Painting",
    location: "Bahadurabad, Karachi",
    experience: 7,
    price: 30,
    priceUnit: "sqft",
    bio: "Interior and exterior painting with a 2-year finish guarantee.",
    rating: 4.5,
    reviewCount: 2,
    available: true,
  },
  {
    id: "seed-6",
    name: "Ayesha Raza",
    business: "QuickFix Appliance Repair",
    service: "Appliance Repair",
    location: "Malir, Karachi",
    experience: 5,
    price: 1200,
    priceUnit: "visit",
    bio: "Same-week repairs for washing machines, fridges, and microwaves.",
    rating: 4.4,
    reviewCount: 3,
    available: true,
  },
];
